# Generated by Django 5.0.3 on 2025-04-22 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreference',
            options={'verbose_name': 'User Preference', 'verbose_name_plural': 'User Preferences'},
        ),
    ]
